using Microsoft.CodeAnalysis;
using System.Linq;
using System.Text;

namespace Monkeymoto.Generators.NativeGenericDelegates.Generator
{
    [Generator]
    internal sealed class Generator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static context =>
                context.AddSource(Constants.DeclarationsSourceFileName, PostInitialization.GetSource()));
            var interfaceSymbols = InterfaceSymbolCollection.GetSymbols(context.CompilationProvider);
            var interfaceReferences = InterfaceReferenceCollection.GetReferences(context, interfaceSymbols);
            var methodReferencesOrDiagnostics = MethodReferenceCollection.GetReferencesOrDiagnostics(interfaceReferences);
            var diagnostics = methodReferencesOrDiagnostics.Select(static (x, _) => x.Item2);
            context.RegisterSourceOutput(diagnostics, static (context, diagnostics) =>
            {
                foreach (var diagnostic in diagnostics)
                {
                    context.ReportDiagnostic(diagnostic);
                }
            });
            var methodReferences = methodReferencesOrDiagnostics.Select(static (x, _) => x.Item1);
            var methodImplementations = MethodImplementationCollection.GetImplementations(methodReferences);
            context.RegisterImplementationSourceOutput(methodImplementations, static (context, methodImplementations) =>
            {
                var sb = new StringBuilder
                (
$@"// <auto-generated>
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace {Constants.RootNamespace}
{{"
                );
                foreach (var methodImplementation in methodImplementations.Implementations)
                {
                    _ = sb.AppendLine().Append(methodImplementation.SourceText);
                }
                _ = sb.AppendLine("}");
                context.AddSource(Constants.SourceFileName, sb.ToString());
            });
        }
    }
}
